# Generated by Django 3.0.5 on 2020-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0041_group_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('playground', 'playground')], max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='theme',
            field=models.TextField(choices=[('foodsaving', 'foodsaving'), ('bikekitchen', 'bikekitchen'), ('general', 'general')]),
        ),
    ]
